
version: 2

jobs:
  # Build & Deploy against development backend
  "build":
    docker:
      - image: maven:3.5.4-jdk-7
    steps:
      # Initialization.
      - run:
          name: Installation of build dependencies.
          command: |
            apt update
            apt install -y  zip jq 
            mkdir ~/awscli
            cd  ~/awscli
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            cd ~
            cd project
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
            ./buildproperties.sh -e DEV -b build.properties,token.properties -k OR
            mvn -B -Dmaven.test.skip=true antrun:run@tokenize package
            git submodule  update --init
            mvn -B -Dmaven.test.skip=true antrun:run@first-deploy
            docker build --rm -f "docker/Dockerfile.base" -t or-dev-base:latest docker

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: [maven-circleci]
